version: "3"

services:
  postgres17:
    container_name: postgres17
    image: postgres:17
    environment:
      TZ: Asia/Seoul
      POSTGRES_DB: demo
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --lc-collate=C --lc-ctype=C'
    ports:
      - 5433:5432
    restart: on-failure
    volumes:
      - demo_postgres17:/var/lib/postgresql/data
      - ./db/initdb.d:/docker-entrypoint-initdb.d:ro
volumes:
  demo_postgres17: